name: Test epydoc

on:
  push:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install tox
      run: |
        python -m pip install --upgrade pip tox

    - name: Install epydoc
      run: |
        cd src
        python setup.py install
        cd ..

    - name: Log system information
      run: |
        test -r /etc/os-release && sh -c '. /etc/os-release && echo "OS: $PRETTY_NAME"'
        python --version
        python -c "print('\nENVIRONMENT VARIABLES\n=====================\n')"
        python -c "import os; [print(f'{k}={v}') for k, v in os.environ.items()]"
    
    - name: Test with python2.7 and python3.8
      run: |
        cd src
        tox 
        cd ..
        